version: '3.9'
services:
  API_Kinopoisk:
    build: /usr/src/Kinopoisk_test_ptoject/
    container-name: API_Kinopoisk_tests
    env_file:
      - cfg.env
    networks:
      - report
    
  Allure_reporter:
    image: "franckescobar/allure-docker-service"
    container-name: Allure_reporter
    environment:
      KEEP_HISTORY: 1
      CHECK_RESULTS_EVERY_SECONDS: 1
    user: "1000:1000"
    ports:
      - "5050:5050"
    volumes:
      - /usr/src/Kinopoisk_test_ptoject/allure-results:/Kinopoisk_test_ptoject/allure-results
      - /usr/src/Kinopoisk_test_ptoject/allure-reports:/Kinopoisk_test_ptoject/allure-reports
    depends_on:
      - API_Kinopoisk
    networks:
      - report
      
networks:
  report:
    driver: bridge
